# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('amount_of_cpu', models.PositiveSmallIntegerField(default=1)),
                ('amount_of_memory', models.FloatField()),
                ('amout_of_hd', models.FloatField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Provider')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.OperationSystem')),
            ],
        ),
    ]
