# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_instance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='amout_of_hd',
            new_name='amount_of_hd',
        ),
    ]
