# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20160712_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardDisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hd_type', models.CharField(choices=[('ssd', 'SSD'), ('hd', 'HD')], max_length=4, verbose_name='Type')),
                ('amount_of_hd', models.FloatField(verbose_name='Hd (GB)')),
            ],
        ),
        migrations.RemoveField(
            model_name='instance',
            name='amount_of_hd',
        ),
    ]
